/**
 * Edge-runtime session helpers for the Next.js proxy.
 *
 * Keep this module free of Node APIs and server-only imports. Route handlers
 * should continue to use auth.ts, which also owns credential and cookie setup.
 */
export const CMS_SESSION_COOKIE = "cms_session";

const CMS_SESSION_MAX_AGE_SECONDS = 8 * 60 * 60;

type CookieStore = {
  set: (name: string, value: string, options: ReturnType<typeof getSessionCookieOptions>) => unknown;
};

type Session = {
  email: string;
  expiresAt: number;
};

function isPlaceholder(value: string) {
  return /^(?:replace|change|your)[-_ ]/i.test(value);
}

function getEdgeAuthConfig() {
  const email = (process.env.CMS_ADMIN_EMAIL || "").trim();
  const sessionSecret = process.env.CMS_SESSION_SECRET || "";

  if (
    !email ||
    !sessionSecret ||
    isPlaceholder(email) ||
    isPlaceholder(sessionSecret) ||
    sessionSecret.length < 32
  ) {
    return null;
  }

  return { email, sessionSecret };
}

function base64UrlToBytes(value: string) {
  if (!/^[A-Za-z0-9_-]+$/.test(value)) return null;

  try {
    const padded = `${value.replace(/-/g, "+").replace(/_/g, "/")}${"=".repeat((4 - (value.length % 4)) % 4)}`;
    const binary = atob(padded);
    const bytes = new Uint8Array(binary.length);

    for (let index = 0; index < binary.length; index += 1) {
      bytes[index] = binary.charCodeAt(index);
    }

    return bytes;
  } catch {
    return null;
  }
}

function getSessionCookieOptions() {
  return {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax" as const,
    path: "/",
    maxAge: CMS_SESSION_MAX_AGE_SECONDS,
  };
}

export function clearSessionCookie(cookieStore: CookieStore) {
  cookieStore.set(CMS_SESSION_COOKIE, "", { ...getSessionCookieOptions(), maxAge: 0 });
}

/**
 * Verifies the HMAC session generated by auth-session.js using the Edge Web
 * Crypto API. This remains async because crypto.subtle is asynchronous.
 */
export async function getAuthenticatedSession(token: string | undefined | null): Promise<Session | null> {
  const config = getEdgeAuthConfig();
  if (!config || !token) return null;

  const [payload, signature, ...extraParts] = token.split(".");
  if (!payload || !signature || extraParts.length) return null;

  const signatureBytes = base64UrlToBytes(signature);
  const decodedPayloadBytes = base64UrlToBytes(payload);
  const payloadBytes = new TextEncoder().encode(payload);
  if (!signatureBytes || !decodedPayloadBytes) return null;

  try {
    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(config.sessionSecret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["verify"]
    );
    const verified = await crypto.subtle.verify("HMAC", key, signatureBytes, payloadBytes);
    if (!verified) return null;

    const payloadJson = new TextDecoder().decode(decodedPayloadBytes);
    const session = JSON.parse(payloadJson);
    const currentTime = Math.floor(Date.now() / 1000);

    if (
      session?.v !== 1 ||
      typeof session.sub !== "string" ||
      !session.sub ||
      !Number.isInteger(session.iat) ||
      !Number.isInteger(session.exp) ||
      session.iat > currentTime + 60 ||
      session.exp <= currentTime ||
      session.exp - session.iat > CMS_SESSION_MAX_AGE_SECONDS ||
      session.sub.toLowerCase() !== config.email.toLowerCase()
    ) {
      return null;
    }

    return { email: config.email, expiresAt: session.exp };
  } catch {
    return null;
  }
}
